services:
  backend:
    image: 97f5d/wordsapp-backend:${VERSION}
    build:
      context: .
      args:
        - build=wordsapp-${VERSION}.jar
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}