services:
  db_prod:
    image: postgres:17
    volumes:
      - prod_db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    environment:
      - POSTGRES_DB=wordsapp
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  
volumes:
  prod_db_data: