create table account_group (
    id bigint generated by default as identity primary key,
    title varchar not null,
    created timestamp default current_timestamp not null ,
    description varchar,
    owner_id bigint references account(id) not null
);