create table word (
    id bigint generated by default as identity primary key not null,
    title               varchar not null,
    language_id         bigint references language(id) not null,
    translations        varchar[],
    definition          varchar,
    description         varchar,
    transcriptions      varchar[],
    created             timestamp default current_timestamp not null
);