create table node (
    id       bigint generated by default as identity primary key not null,
    group_id bigint references account_group(id) not null,
    word_id  bigint references word(id) not null
);